spring:
  application:
    name: ADMIN-CLIENT
  boot:
    admin:
      client:
        url: http://localhost:8001
server:
  port: 8002

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:9999/eureka
